# Generated by Django 4.1.7 on 2023-04-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
