# Generated by Django 4.1.7 on 2023-04-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
