# Generated by Django 4.1.7 on 2023-05-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to=''),
        ),
    ]
